device: auto
logdir: ./debug/
comment: ''
seed: null
deterministic: false
steps: 1000000
eval_every: 10000
video_every: 10000
save_every: 10000
eval_episodes: 5
log_every: 1000
log_scalars: true
log_images: true
task: cartpole_balance
envs: 1
action_repeat: 2
time_limit: 1000
prefill: 100
eval_noise: 0.0
clip_rewards: none
deter_size: 200
stoch_size: 30
num_units: 400
dense_act: elu
cnn_act: relu
cnn_depth: 32
pcont: false
free_nats: 3.0
kl_scale: 1.0
pcont_scale: 10.0
weight_decay: 0.0
batch_size: 10
batch_length: 10
train_every: 1000
train_steps: 2
model_lr: 0.0006
value_lr: 8.0e-05
actor_lr: 8.0e-05
grad_clip: 100.0
dataset_balance: false
discount: 0.99
disclam: 0.95
horizon: 15
action_dist: tanh_normal
action_init_std: 5.0
expl: additive_gaussian
expl_amount: 0.3
expl_decay: 0.0
expl_min: 0.0
update_horizon: null
single_step_q: false
tf_init: false
